# Generated by Django 3.1 on 2020-09-21 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=255, verbose_name='Описание типа вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=255, verbose_name='Описание типа ценности ответа')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения квиза')),
                ('date', models.DateField(default='1970-01-01', verbose_name='Дата проведения квиза')),
            ],
        ),
        migrations.CreateModel(
            name='EventState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=255, verbose_name='Состояние события')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название квиза')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0, verbose_name='Номер тура в квизе')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема тура')),
                ('cost_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizApp.cost')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApp.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=32, verbose_name='Идентификатор сессии')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название команды')),
                ('slogan', models.CharField(default='', max_length=255, verbose_name='Девиз команды')),
                ('event_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quizApp.event')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(default='1970-01-01 00:00:00', verbose_name='Время начала тура')),
                ('time_stop', models.DateTimeField(default='1970-01-01 00:00:00', verbose_name='время конца тура')),
                ('event_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quizApp.event')),
                ('tours_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quizApp.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Номер вопроса в туре')),
                ('correct', models.CharField(default='', max_length=1000, verbose_name='Правильный ответ')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Описание')),
                ('answer_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApp.answertype')),
                ('tours_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApp.tour')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApp.eventstate'),
        ),
        migrations.AddField(
            model_name='event',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApp.quiz'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(blank=True, default=0, verbose_name='Ставка')),
                ('answer', models.CharField(default='', max_length=1000, verbose_name='Ответ команды')),
                ('correct', models.BooleanField(default='', verbose_name='Правильный ли был ответ')),
                ('questions_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quizApp.question')),
                ('team_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quizApp.team')),
            ],
        ),
    ]
