# Generated by Django 3.1 on 2020-09-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='tours_id',
            new_name='tour_id',
        ),
    ]
