# Generated by Django 3.1 on 2020-09-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0003_auto_20200924_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='time_start',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время начала тура'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='time_stop',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='время конца тура'),
        ),
    ]
